apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: gcr.io/qwiklabs-gcp-01-5be1cb360377/sample-app:v2.0
        ports:
        - containerPort: 8080
